export const RESULTS_LIMIT = 10 as const;

export const CategoriesList: Record<string, string> = {
  social: "Social",
  news: "News",
  sports: "Sports",
  education: "Education",
  health: "Health",
  magazine: "Magazine",
  comics: "Comics",
  stories: "Stories",
  manga: "Manga",
  travel: "Travel",
  game: "Game",
  movie: "Movie",
  business: "Business",
  food: "Food",
  ai: "AI",
  tech: "Tech",
  history: "History",
  life: "Life",
  science: "Science",
  nature: "Nature",
  review: "Review",
  fashion: "Fashion",
  shop: "Shop",
  poem: "Poem",
} as const;

export const LanguageList = {
  EN: "English",
  TR: "Turkish",
  ES: "Spanish",
  FR: "French",
  DE: "German",
  IT: "Italian",
  CN: "Chinese",
  JP: "Japanese",
  RU: "Russian",
  AR: "Arabic",
  PT: "Portuguese",
  HI: "Hindi",
  KO: "Korean",
  NL: "Dutch",
  SV: "Swedish",
  NO: "Norwegian",
  DA: "Danish",
  FI: "Finnish",
} as const;
